### ISSUE TITLE
End Key Crash

### ISSUE THREAD

**Issue by Moodlecowman** [Echorridoors/Verreciel#7]
Directly after completing the End Key, trying to route it from the cargo into any Portal crashes the game. Likely to occur at any point after acquiring the key, but before unlocking the Close.

While not a problem during the normal flow of the game, since one must go out of their way to encounter it, the crash has been reliably reproduced on multiple devices.

**Comment by neauoire** [comment]
Thanks for pointing that out, I was able to reproduce it.
Will fix.
